### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by xinsongyan** [rmcgibbo/quadprog#8] opened 2020-04-27 18:06 UTC
No idea why this happens to my new laptop. The same code works for the old one.

File "quadprog/quadprog.pyx", line 91, in quadprog.solve_qp
TypeError: 'float' object cannot be interpreted as an integer

**Comment by rmcgibbo** [comment] 2020-04-27 18:28
This might be a duplicate of https://github.com/rmcgibbo/quadprog/issues/6. Are you installing from the current master branch on github?

**Comment by xinsongyan** [comment] 2020-04-27 18:30
I am using python3.6, I think it is installed by qpsolvers from https://pypi.org/project/qpsolvers/

**Comment by xinsongyan** [comment] 2020-04-27 18:31
qpsolvers (1.1)
quadprog (0.1.7)

**Comment by rmcgibbo** [comment] 2020-04-27 18:32
Can you trying directly installing the github master branch?

**Comment by xinsongyan** [comment] 2020-04-27 18:40
I got the same error.

**Comment by xinsongyan** [comment] 2020-04-27 18:42
sudo python3 setup.py install

and tried this:

from numpy import array, dot
from qpsolvers import solve_qp

M = array([[1., 2., 0.], [-8., 3., 2.], [0., 1., 1.]])
P = dot(M.T, M)  # quick way to build a symmetric matrix
q = dot(array([3., 2., 3.]), M).reshape((3,))
G = array([[1., 2., 1.], [2., 0., 1.], [-1., 2., -1.]])
h = array([3., 2., -2.]).reshape((3,))
A = array([1., 1., 1.])
b = array([1.])

print("QP solution:", solve_qp(P, q, G, h, A, b))

got this:

>>> print( "QP solution:", solve_qp(P, q, G, h, A, b))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    print( "QP solution:", solve_qp(P, q, G, h, A, b))
  File "/usr/local/lib/python3.6/dist-packages/qpsolvers/__init__.py", line 187,
 in solve_qp
    return quadprog_solve_qp(P, q, G, h, A, b, initvals=initvals)
  File "/usr/local/lib/python3.6/dist-packages/qpsolvers/quadprog_.py", line 81,
 in quadprog_solve_qp
    return solve_qp(qp_G, qp_a, qp_C, qp_b, meq)[0]
  File "quadprog/quadprog.pyx", line 91, in quadprog.solve_qp
TypeError: 'float' object cannot be interpreted as an integer

**Comment by xinsongyan** [comment] 2020-04-27 18:44
wait, it is calling the other one, I will use the native one.

**Comment by rmcgibbo** [comment] 2020-04-27 18:45
You need to do some special steps to install from github. The default `pip install` is pulling from pypi.

**Comment by xinsongyan** [comment] 2020-04-27 18:47
I downloaded the source code and install with 'sudo python3 setup.py install', is this enough?

**Comment by xinsongyan** [comment] 2020-04-27 18:49
with 'sudo python3 setup.py install', I got: 

running install
running bdist_egg
running egg_info
writing quadprog.egg-info/PKG-INFO
writing dependency_links to quadprog.egg-info/dependency_links.txt
writing requirements to quadprog.egg-info/requires.txt
writing top-level names to quadprog.egg-info/top_level.txt
reading manifest file 'quadprog.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxd' anywhere in distribution
writing manifest file 'quadprog.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
skipping 'quadprog/quadprog.cpp' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/quadprog.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for quadprog.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/quadprog.py to quadprog.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying quadprog.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/quadprog-0.1.7-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing quadprog-0.1.7-py3.6-linux-x86_64.egg
removing '/usr/local/lib/python3.6/dist-packages/quadprog-0.1.7-py3.6-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/quadprog-0.1.7-py3.6-linux-x86_64.egg
Extracting quadprog-0.1.7-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
quadprog 0.1.7 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/quadprog-0.1.7-py3.6-linux-x86_64.egg
Processing dependencies for quadprog==0.1.7
Searching for Cython==0.29.17
Best match: Cython 0.29.17
Adding Cython 0.29.17 to easy-install.pth file
Installing cygdb script to /usr/local/bin
Installing cython script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for quadprog==0.1.7

Looks successfully installed.

**Comment by xinsongyan** [comment] 2020-04-27 18:51
Then I tried:

>>> from quadprog import solve_qp
>>> from numpy import array, dot
>>> M = array([[1., 2., 0.], [-8., 3., 2.], [0., 1., 1.]])
>>> P = dot(M.T, M)  # quick way to build a symmetric matrix
>>> q = dot(array([3., 2., 3.]), M).reshape((3,))
>>> solve_qp(P,q)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    solve_qp(P,q)
  File "quadprog/quadprog.pyx", line 91, in quadprog.solve_qp
TypeError: 'float' object cannot be interpreted as an integer

**Comment by xinsongyan** [comment] 2020-04-27 18:52
>>> import quadprog
>>> print(quadprog.__file__)
/usr/local/lib/python3.6/dist-packages/quadprog.cpython-36m-x86_64-linux-gnu.so

**Comment by rmcgibbo** [comment] 2020-04-27 20:21
Okay, I am trying to reproduce this on my machine. So far I've installed the master branch using python3.7 and Cython 0.29.17, and not been able to trigger this error. Next I will try python 3.6

**Comment by rmcgibbo** [comment] 2020-04-27 21:29
I was not able to reproduce this on python3.6 either.

**Comment by xinsongyan** [comment] 2020-04-27 21:31
I have  pretty much the same system setup on the other laptop and it works. Really weird.

**Comment by xinsongyan** [comment] 2020-04-28 13:07
I tried to remove the pip installed qpsolvers and quadprog, then the one installed from source works. I think multiple installations messed up. solved! Thanks!

**Closed** 2020-04-28 13:07 UTC

**Comment by anhtu812** [comment] 2020-09-17 07:34
I solved same problem by install Cython==0.28.2 and quadprog==0.1.7
